### ISSUE TITLE
Disabling warning message when running keg: adding `-f` to `LESS`

### ISSUE THREAD

**Issue by sderev** [rwxrob/keg#59]
As for the `export LESS=-r`, another recommendation could be made to users: **adding the flag `-f` to `LESS` will disable this warning message (cf. below) when keg runs.**

![image](https://user-images.githubusercontent.com/24412384/204090969-b60e76f2-a3bd-4afa-9e13-9d73684a48b5.png)

**Comment by rwxrob** [comment]
Yeah, ran into that and was adding it to the help documentation. The hard part is that we never know what the `pager` program is. We could do some symlink resolution to get it and add the -fR to the actual command saving the user from doing it. This is going to be a constant problem because people are not going to realize what is going on.

**Comment by rwxrob** [comment]
Turns out `git` is completely ignoring the `pager` binary and only recognizes `PAGER` and `GIT_PAGER` setting default pager to `less` automatically. I feel like that is cheating, but that's what I'm going to do.

**Comment by rwxrob** [comment]
For the record, I decided to do the right thing and recognize /usr/bin/pager anyway (screw git) and add the LESS and LV fixes that it does automatically so that `less` works if it is symlinked to `pager` so we should have no issues at all with telling users about `export LESS`.
