### ISSUE TITLE
Suggestion: `keg search`

### ISSUE THREAD

**Issue by sderev** [rwxrob/keg#66]
It could be nice to be able to search inside all of the content of a node, and not only the titles.

Maybe, a `-t` flag or a dedicated command could also search for tags only.

**Comment by rwxrob** [comment]
Well this has (rather obviously) always been the goal. There are already several tickets on this and I've been talking about it for more than three years.  Not only will it be searchable, but there will be a full words index as well enabling FTS searching of *every* keg that someone follows.

This requires a proper parser (rather than just grepping, which anyone can do now) which depends on the kegml subpackage.

I do want to emphasize that there will *never* be any flags or switches on anything, ever. This stuff all uses Bonzai and we *hate* getopt. For reasons check out https://github.com/rwxrob/bonzai
