### ISSUE TITLE
Keg fails to commit changes to git

### ISSUE THREAD

**Issue by bart-jaskulski** [rwxrob/keg#87]
Integration with git fails in different cases.

1. `keg init` on fresh git repository, without any commit and live remote repo
2. `keg init` on living git repository
3. `keg create` on living git repository

First case is when I want to create brand new keg integrated with github repository. I don't do anything unusual (I think), just
```bash
mkdir keg
cd keg
git init
git add remote origin git@github.com:repo/repo.git # Fresh repo, without any online commits
keg init
```

After I exit the editor, I face message that git failed to pull data from repository and I should set remote tracking.

If I try to repeat the same on actual repository, with some history, the path is similar - exiting `keg init` fails with message that it couldn't pull data from remote repository (no info about failed tracking url).

Finally, after I manually commit changes introduced by `keg init` and try to create new node with `keg create` (either on fresh repo or living one) git errors following
```
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.
```

**Comment by rwxrob** [comment]
This is because you haven't gotten the git repo successfully pushed before calling `keg init`, which calls `Publish` internally which does the following:

```
git pull
git add DIR/README.md
git commit -m 'TITLE'
git push
```

We have a few options here:

1. Update the `init` help info to explain successful git setup, first
1. Drop all `git` stuff from `Publish` just for `keg init`
1. Don't do any `git` stuff at all with `keg init`
1. Integrate `git init` into `keg init` and prompt to make `git init` easier
1. Integrate `gh` support as well so we can actually create remote `keg`

Considering that most people will be saving their kegs to GitHub specifically, I think the last two options combined might be the most convenient for people long term. That way anyone wanting a new keg would just have to make a directory and `keg init` to do *everything* needed to bootstrap including creating the remote repository with a `docs` directory and GitHub Pages even activated.

**Comment by rwxrob** [comment]
Okay, I've added a much better Getting Started section to the main help. It's the easiest since everything else is just making assumptions about an individuals `git` and GitHub workflows and we can't account for them all. Perhaps someday we'll fully incorporate GitHub support, but the idea isn't that people will be creating new standalone repos for many kegs, but support one primary one and others in the `docs` directories of software projects and such.
